name: 'cache-make'
description: 'Use makefile with action/cache'
branding:
  icon: box
  color: red
inputs:
  past-ref:
    description: "commit id, tag, etc."
    required: false
  current-ref:
    description: "commit id, tag, etc."
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        # Get past reference
        if [ -z ${{ inputs.past-ref }} ]; then
          before=$(git rev-parse HEAD |xargs git cat-file -p | grep parent | awk '{print $2}')
        else
          before=${{ inputs.past-ref }}
        fi;

        # Get current reference
        if [ -z ${{ input.current-ref }} ]; then
          after=${{ github.sha }}
        else
          after=$(git rev-parse HEAD |xargs git cat-file -p | grep parent | awk '{print $2}')
        fi;

        # Change time
        ${{ github.action_path }}/get_unchanged_files.sh $before $after
      shell: bash
