name: 'cache-make'
description: 'Use makefile with action/cache'
branding:
  icon: box
  color: red
inputs:
  before-ref:
    description: "commit id, tag, etc."
    required: false
  after-ref:
    description: "commit id, tag, etc."
    required: false
runs:
  using: "composite"
  steps:
    - run: |
        # Get past reference
        if [ -z ${{ inputs.before-ref }} ]; then
          before=$(git rev-parse HEAD |xargs git cat-file -p | grep parent | awk '{print $2}')
        else
          before=${{ inputs.before-ref }}
        fi;

        # Get current reference
        if [ -z ${{ inputs.after-ref }} ]; then
          after=${{ github.sha }}
        else
          after=${{ inputs.after-ref }}
        fi;

        # Change time
        cd $GITHUB_WORKSPACE
        ${{ github.action_path }}/get_unchanged_files.sh $before $after
      shell: bash
