name: Build

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Setup cache
        uses: actions/cache@v2
        with:
          path: dist
          key: ${{ runner.os }}-makefile-${{ hashFiles('makefile') }}
          restore-keys: |
            ${{ runner.os }}-makefile-

      - name: Check pre-environment
        run: ls -la --full-time
      
      - name: Check dist directory
        run: ls -la --full-time dist/
      
      - name: Send unchanged files to past
        run: ./get_unchanged_files.sh $(git rev-parse HEAD) $(git rev-parse HEAD |xargs git cat-file -p | grep parent | awk '{print $2}')

      - name: Build
        run: make

      - name: Check post-environment
        run: ls -la --full-time
      
      - name: Check dist directory
        run: ls -la --full-time dist/
